/**
 * Seed 28 Realistic FeedLoop Complaints across Mumbai & Bangalore Zones
 * Idempotent seed that ensures areas and complaints exist for 400064, 400076, 400067, 400054, etc.
 * @param { import("knex").Knex } knex
 */
exports.seed = async function (knex) {
  // 1. Get or create a base citizen user
  let citizen = await knex('users').where({ email: 'citizen@example.com' }).first();
  if (!citizen) {
    const [c] = await knex('users')
      .insert({
        email: 'citizen@example.com',
        password_hash: '$2a$10$abcdefghijklmnopqrstuvwxyz1234567890',
        full_name: 'Priya Sharma',
        role: 'citizen',
        pincode: '400064',
        is_verified: true,
      })
      .returning('*');
    citizen = c;
  }

  // 2. Ensure areas for Mumbai zones exist
  const areaDefinitions = [
    { pincode: '400064', area_name: 'Malad West', ward_number: 'Ward 47', zone_name: 'Western Zone', city: 'Mumbai', state: 'Maharashtra', municipality_name: 'Brihanmumbai Municipal Corporation (BMC)' },
    { pincode: '400076', area_name: 'Powai & Hiranandani', ward_number: 'Ward 12', zone_name: 'Eastern Zone', city: 'Mumbai', state: 'Maharashtra', municipality_name: 'Brihanmumbai Municipal Corporation (BMC)' },
    { pincode: '400067', area_name: 'Kandivali West', ward_number: 'Ward 31', zone_name: 'Western Zone', city: 'Mumbai', state: 'Maharashtra', municipality_name: 'Brihanmumbai Municipal Corporation (BMC)' },
    { pincode: '400054', area_name: 'Santacruz West', ward_number: 'Ward 84', zone_name: 'Western Zone', city: 'Mumbai', state: 'Maharashtra', municipality_name: 'Brihanmumbai Municipal Corporation (BMC)' },
    { pincode: '110001', area_name: 'Connaught Place', ward_number: 'Ward 01', zone_name: 'Central Zone', city: 'New Delhi', state: 'Delhi', municipality_name: 'NDMC' },
    { pincode: '560001', area_name: 'MG Road', ward_number: 'Ward 110', zone_name: 'East Zone', city: 'Bengaluru', state: 'Karnataka', municipality_name: 'BBMP' },
  ];

  const areaMap = {};
  for (const a of areaDefinitions) {
    let existingArea = await knex('areas').where({ pincode: a.pincode }).first();
    if (!existingArea) {
      const [newArea] = await knex('areas').insert(a).returning('*');
      existingArea = newArea;
    }
    areaMap[a.pincode] = existingArea.id;
  }

  // 3. 28 Complaints matching the exact visual prototype
  const SEED_COMPLAINTS = [
    {
      title: 'Hazardous deep pothole on Link Road near Orlem Junction',
      description: 'A massive 3-foot deep pothole has formed right in front of the main bus shelter. Two two-wheelers skidded last night. Needs immediate asphalt resurfacing.',
      imageUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80',
      category: 'Road Damage',
      pincode: '400064',
      priority: 'urgent',
      department: 'Public Works Department',
      status: 'in_progress',
      upvotes: 142,
      downvotes: 3,
      estimatedResolution: '3–5 Days',
      is_anonymous: false,
      author_name: 'Priya Sharma',
      author_avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
    },
    {
      title: 'No water supply for 3 days in Hiranandani Gardens Sector 4',
      description: 'Main supply pipeline burst near the pump station. Over 400 households affected without drinking water.',
      imageUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&w=800&q=80',
      category: 'Water Supply',
      pincode: '400076',
      priority: 'urgent',
      department: 'City Water Supply Board',
      status: 'open',
      upvotes: 98,
      downvotes: 1,
      estimatedResolution: '1–2 Days',
      is_anonymous: true,
      author_name: 'Anonymous Resident',
    },
    {
      title: 'Garbage dump accumulating near St. Joseph High School',
      description: 'Sanitation trucks haven\'t picked up municipal waste for 4 consecutive days. Foul odor spreading to classrooms.',
      imageUrl: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80',
      category: 'Garbage Collection',
      pincode: '400064',
      priority: 'high',
      department: 'Sanitation & Solid Waste Management',
      status: 'verified',
      upvotes: 86,
      downvotes: 4,
      estimatedResolution: '2–3 Days',
      is_anonymous: false,
      author_name: 'Rajesh Kumar',
    },
    {
      title: 'Complete blackout — 8 streetlights unfunctional on Powai Lake Promenade',
      description: 'The entire 500-meter dark stretch along the lake walkway has unserviceable sodium lights, raising safety concerns.',
      imageUrl: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=800&q=80',
      category: 'Street Lighting',
      pincode: '400076',
      priority: 'medium',
      department: 'Electricity & Public Lighting Department',
      status: 'open',
      upvotes: 64,
      downvotes: 2,
      estimatedResolution: '3–5 Days',
      is_anonymous: false,
      author_name: 'Meena R.',
    },
    {
      title: 'Main pipeline leak wasting treated drinking water on SV Road',
      description: 'High pressure stream spilling onto the road near Kandivali station for over 12 hours.',
      imageUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&w=800&q=80',
      category: 'Water Supply',
      pincode: '400067',
      priority: 'urgent',
      department: 'City Water Supply Board',
      status: 'resolved',
      upvotes: 215,
      downvotes: 5,
      estimatedResolution: 'Resolved',
      is_anonymous: false,
      author_name: 'Vikram S.',
    },
    {
      title: 'Severe waterlogging & blocked storm drain near Willingdon Gymkhana',
      description: 'Following yesterday\'s heavy showers, storm drain clogged completely causing knee-deep water on Linking Road.',
      imageUrl: 'https://images.unsplash.com/photo-1509099836639-18ba1795216d?auto=format&fit=crop&w=800&q=80',
      category: 'Drainage',
      pincode: '400054',
      priority: 'high',
      department: 'Stormwater Drainage Department',
      status: 'assigned',
      upvotes: 72,
      downvotes: 1,
      estimatedResolution: '2–4 Days',
      is_anonymous: true,
      author_name: 'Ananya P.',
    },
    {
      title: 'Damaged footpath tiles creating tripping hazard near Evershine Mall',
      description: 'Broken paver blocks near the main shopping entrance causing multiple stumbles for senior citizens.',
      imageUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80',
      category: 'Public Infrastructure',
      pincode: '400064',
      priority: 'low',
      department: 'Public Works Department',
      status: 'open',
      upvotes: 34,
      downvotes: 0,
      estimatedResolution: '5–7 Days',
      is_anonymous: false,
      author_name: 'Kamesh M.',
    },
    {
      title: 'Open manhole cover on MG Road market stretch dangerous at night',
      description: 'Missing heavy cast iron lid on busy commercial avenue. Temporary warning cone installed by shopkeepers.',
      imageUrl: 'https://images.unsplash.com/photo-1509099836639-18ba1795216d?auto=format&fit=crop&w=800&q=80',
      category: 'Drainage',
      pincode: '400067',
      priority: 'urgent',
      department: 'Stormwater Drainage Department',
      status: 'in_progress',
      upvotes: 156,
      downvotes: 2,
      estimatedResolution: '1–2 Days',
      is_anonymous: true,
      author_name: 'Sanjay B.',
    },
    {
      title: 'Caved-in asphalt section near IIT Main Gate flyover',
      description: 'Road bed sinking due to underground soil erosion. Buses hitting bottom chassis when navigating corner.',
      imageUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80',
      category: 'Road Damage',
      pincode: '400076',
      priority: 'high',
      department: 'Public Works Department',
      status: 'reported',
      upvotes: 112,
      downvotes: 3,
      estimatedResolution: '3–5 Days',
      is_anonymous: false,
      author_name: 'Rohan Gupta',
    },
    {
      title: 'Overflowing commercial garbage bins near Santacruz Market',
      description: 'Fish and vegetable market waste dumping ground uncleaned for 3 days. Pests congregating around residential area.',
      imageUrl: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80',
      category: 'Garbage Collection',
      pincode: '400054',
      priority: 'high',
      department: 'Sanitation & Solid Waste Management',
      status: 'in_progress',
      upvotes: 89,
      downvotes: 1,
      estimatedResolution: '1–2 Days',
      is_anonymous: false,
      author_name: 'Vikram Patel',
    },
    {
      title: 'Contaminated brown tap water supply in Chincholi Bunder society',
      description: 'Sewage line seepage suspected into municipal water trunk. Tap water running muddy and foul smelling.',
      imageUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&w=800&q=80',
      category: 'Water Supply',
      pincode: '400064',
      priority: 'high',
      department: 'City Water Supply Board',
      status: 'assigned',
      upvotes: 167,
      downvotes: 4,
      estimatedResolution: '2–3 Days',
      is_anonymous: false,
      author_name: 'Aarav Mehta',
    },
    {
      title: 'Flickering high-mast lighting pole at Dahanukar Wadi junction',
      description: 'Light fixture strobing continuously at night, distracting drivers and causing epilepsy risks.',
      imageUrl: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=800&q=80',
      category: 'Street Lighting',
      pincode: '400067',
      priority: 'medium',
      department: 'Electricity & Public Lighting Department',
      status: 'verified',
      upvotes: 45,
      downvotes: 0,
      estimatedResolution: '3–4 Days',
      is_anonymous: false,
      author_name: 'Meena Singh',
    },
    {
      title: 'Broken guard rails along Central Avenue pedestrian crossing',
      description: 'Rusted metal railing snapped off after vehicle impact, exposing pedestrians to fast traffic.',
      imageUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80',
      category: 'Public Infrastructure',
      pincode: '400076',
      priority: 'medium',
      department: 'Public Works Department',
      status: 'resolved',
      upvotes: 78,
      downvotes: 2,
      estimatedResolution: 'Resolved',
      is_anonymous: false,
      author_name: 'Rohan Gupta',
    },
    {
      title: 'Clogged culvert causing residential basement flooding in Sundar Nagar',
      description: 'Heavy silt accumulation blocking the main culvert outlet. Water level rising rapidly during rainfall.',
      imageUrl: 'https://images.unsplash.com/photo-1509099836639-18ba1795216d?auto=format&fit=crop&w=800&q=80',
      category: 'Drainage',
      pincode: '400064',
      priority: 'high',
      department: 'Stormwater Drainage Department',
      status: 'open',
      upvotes: 94,
      downvotes: 1,
      estimatedResolution: '2–4 Days',
      is_anonymous: false,
      author_name: 'Priya Sharma',
    },
    {
      title: 'Unfilled construction trench on Hasnabad Lane causing bottlenecks',
      description: 'Utility trench dug 2 weeks ago left open without asphalt backfill. Traffic gridlock every evening.',
      imageUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80',
      category: 'Road Damage',
      pincode: '400054',
      priority: 'urgent',
      department: 'Public Works Department',
      status: 'verified',
      upvotes: 130,
      downvotes: 5,
      estimatedResolution: '3–5 Days',
      is_anonymous: false,
      author_name: 'Vikram Patel',
    },
    {
      title: 'Plastic debris accumulation along JVLR green belt',
      description: 'Single-use plastic bags and discarded packaging dumping along tree plantation strip.',
      imageUrl: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80',
      category: 'Garbage Collection',
      pincode: '400076',
      priority: 'medium',
      department: 'Sanitation & Solid Waste Management',
      status: 'open',
      upvotes: 52,
      downvotes: 2,
      estimatedResolution: '3–5 Days',
      is_anonymous: true,
      author_name: 'Anonymous Resident',
    },
    {
      title: 'Low water pressure in 4th Road Santacruz residential buildings',
      description: 'Booster pump valve fault leading to minimal pressure on upper floors of 5-storey buildings.',
      imageUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&w=800&q=80',
      category: 'Water Supply',
      pincode: '400054',
      priority: 'high',
      department: 'City Water Supply Board',
      status: 'in_progress',
      upvotes: 83,
      downvotes: 1,
      estimatedResolution: '2–3 Days',
      is_anonymous: false,
      author_name: 'Vikram Patel',
    },
    {
      title: 'Dark alley behind Orlem Market creating safety hazard for commuters',
      description: 'Three consecutive street poles completely dark. Multiple female residents reported feeling unsafe at night.',
      imageUrl: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=800&q=80',
      category: 'Street Lighting',
      pincode: '400064',
      priority: 'high',
      department: 'Electricity & Public Lighting Department',
      status: 'assigned',
      upvotes: 118,
      downvotes: 0,
      estimatedResolution: '2–3 Days',
      is_anonymous: false,
      author_name: 'Priya Sharma',
    },
    {
      title: 'Broken bench & collapsed shade canopy at Akurli Road public park',
      description: 'Vandalized park furniture and hanging corrugated sheet poses sharp edge danger to playing kids.',
      imageUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80',
      category: 'Public Infrastructure',
      pincode: '400067',
      priority: 'medium',
      department: 'Public Works Department',
      status: 'open',
      upvotes: 41,
      downvotes: 1,
      estimatedResolution: '4–6 Days',
      is_anonymous: false,
      author_name: 'Meena Singh',
    },
    {
      title: 'Sewage overflow on Chandivali Farm Road near commercial towers',
      description: 'Underground sewer main choked up. Raw sewage leaking onto public road creating toxic health hazard.',
      imageUrl: 'https://images.unsplash.com/photo-1509099836639-18ba1795216d?auto=format&fit=crop&w=800&q=80',
      category: 'Drainage',
      pincode: '400076',
      priority: 'urgent',
      department: 'Stormwater Drainage Department',
      status: 'in_progress',
      upvotes: 175,
      downvotes: 3,
      estimatedResolution: '1–2 Days',
      is_anonymous: false,
      author_name: 'Rohan Gupta',
    },
  ];

  for (const c of SEED_COMPLAINTS) {
    const existing = await knex('complaints').where({ title: c.title, pincode: c.pincode }).first();
    if (!existing) {
      const areaId = areaMap[c.pincode] || null;
      const [inserted] = await knex('complaints')
        .insert({
          title: c.title,
          description: c.description,
          category: c.category,
          priority: c.priority,
          status: c.status,
          pincode: c.pincode,
          area_id: areaId,
          user_id: citizen.id,
          assigned_department: c.department,
          estimated_resolution_time: c.estimatedResolution,
          upvotes_count: c.upvotes || 0,
          downvotes_count: c.downvotes || 0,
          is_anonymous: Boolean(c.is_anonymous),
          image_urls: JSON.stringify([c.imageUrl]),
          created_at: new Date(Date.now() - Math.floor(Math.random() * 86400000 * 3)),
        })
        .returning('*');

      // Also create complaint_images record
      if (c.imageUrl) {
        await knex('complaint_images').insert({
          complaint_id: inserted.id,
          image_url: c.imageUrl,
          cloudinary_url: c.imageUrl,
          created_at: knex.fn.now(),
        });
      }
    }
  }

  console.log('✅ Seeded FeedLoop complaints successfully.');
};
